language: node_js

sudo: false

addons:
  apt:
    packages:
      - xvfb
      - gnome-keyring
      - libgnome-keyring-dev

env:
  - CC=clang CXX=clang++ npm_config_clang=1

node_js:
  - "6.0"
  - "4.0"
  - "0.11"
  - "0.10"
  - "iojs"

notifications:
  email: false

script: xvfb-run ./script/cibuild

git:
  depth: 10

branches:
  only:
    - master
